[project]
name = "tensor-network-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
    "physics-tenpy>=1.1.0",
    "scipy>=1.17.0",
]
